### PR TITLE
Rename license files to make this package's docs visible on pkg.go.dev

### PR DESCRIPTION
**Pull request by autarch**
The pkg.go.dev site will not display a package's docs unless it can determine
that package's license. It's ability to do that is based in part on the names
of the license files.

This commit renames this repo's license files to names that pkg.go.dev should
recognize.

### CODE REVIEW

**Comment by swinslow** [comment]
LGTM, thanks @autarch! I wasn't aware of the pkg.go.dev requirements here.

**Comment by autarch** [comment]
Yay, it worked! github.com/spdx/tools-golang

**Comment by autarch** [comment]
Oops, wrong link - https://pkg.go.dev/github.com/spdx/tools-golang

**Comment by autarch** [comment]
Oh, it didn't work yet. I was getting too excited. I think this won't be detected until there's a new tag in the repo.

**Comment by swinslow** [comment]
Ah, gotcha. I'll look to push a new tag soon, I think there are some other pending PRs that I need to merge in soon as it is  :)

**Pull request merged**
