### PR TITLE
[GSoC'21] Pr:4 . Complete the JSON parser

### PR DESCRIPTION
**Pull request by specter25**
GSoC'2021 Pull Request 4 :
Deliverables Completed :

- [x] Parse Reviews 
- [x]  Write tests for review parser
- [x]  Package Excludes File property handled for presence and absence of "excludes:" prefix
- [x] Static range parsing of snippets changed to dynamic

### CODE REVIEW

**Comment by specter25** [comment]
cc @swinslow 

Hey Steve I am getting the DCO failure on changing the name to Ujjwal Agarwal from specter25
Screenshot from 2021-06-26 17-39-11

**Comment by specter25** [comment]
cc @swinslow 
I have parsed the reviews  add added compatibility to check whether the "excludes:" prefix is there in the packageExcludesFiles property or not .

**Review by swinslow — APPROVED** [review]
Great work, @specter25! Merging now.

In the next few days I'll plan to merge this into the main branch, and will then issue a new release that incorporates this parser. Thanks for all your work on this so far.

**Comment by specter25** [comment]
Most welcome @swinslow  :)

**Pull request merged**
