### PR TITLE
Converter from Main to Intermediate data structure 

### PR DESCRIPTION
**Pull request by abhishekspeer**
Signed-off-by: abhishekspeer.abhishek.abhishekgaur.gaur@gmail.com

Transfer script added to Convert from Main to Intermediate data structure.

### CODE REVIEW

**Comment by abhishekspeer** [comment]
Hi @swinslow. I've added the code to convert back from Main data structure to Intermediate data structure via this PR. Considering the current standard data structure we have, it's certainly not possible for us to store all the extracted data from the Intermediate structure. I've tried to include everything that what was possible. I'll try to improve this by making more changes in future. :)

**Comment by swinslow** [comment]
Looks good! I won't be able to test this fully until the DCO sign-offs are fixed for #14 (so I can merge it and #19). But this is fine to merge now.

**Comment by swinslow** [comment]
Actually, wait, the PR here is to spdx:master, but it should be spdx:rdfreader instead. 

@abhishekspeer can you fix that, and/or submit a new PR if that's what required? I don't want to merge this into the master branch yet.

**Comment by abhishekspeer** [comment]
Hi @swinslow, apologies for that -- I've changed that base branch from master to rdfreader. You can merge it now, or let me know if there is anything else I need to change. :)

**Pull request merged**
