### PR TITLE
Add rdfSaver Files

### PR DESCRIPTION
**Pull request by abhishekspeer**
Signed-off-by: abhishekspeer <abhishek.abhishekgaur.gaur@gmail.com>

RDF writer support is added via this pull request.

### CODE REVIEW

**Comment by abhishekspeer** [comment]
Hi @swinslow, I've added the code to convert intermediate data structure to standard data structure with this commit. Please have a look and let me know in case you expect any changes 
Now completing the code to convert standard data structure into intermediate data data structure. :)

**Comment by rtgdk** [comment]
@abhishekspeer Open a separate PR for that. Since we want to merge that code with rdf-reader branch and see the reader part running. This PR is just for rdfsaver.

**Comment by abhishekspeer** [comment]
Thanks @rtgdk! I've referenced a separate PR for that. Please have a look and let me know if there is anything I should change. :)

**Comment by swinslow** [comment]
@abhishekspeer Did you see that the DCO sign-off check is failing? It appears that some of the commits are missing the DCO sign-off (see the "Details" button next to the DCO line in the checks box). 

Can you please amend those commits or if necessary squash and re-submit as one commit with the DCO sign-off corrected?

**Comment by abhishekspeer** [comment]
@swinslow I have made the required changes you suggested and DCO passes now. Please let me know if there is anything else I need to change. Thanks! :)

**Comment by swinslow** [comment]
Thanks @abhishekspeer!

**Pull request merged**
