### PR TITLE
Add rdfReader files

### PR DESCRIPTION
**Pull request by abhishekspeer**
RDF Parser support is added via this pull request.

### CODE REVIEW

**Comment by swinslow** [comment]
Hi @abhishekspeer, as we discussed you'll want to modify the import paths for some of the files so that they use `github.com/spdx/tools-golang/` -- that appears to be why the CI checks are failing.

You may also want to consider changing the directory and package names from `rdf` to `rdfloader` in order to mirror how the tag-value packages are set up (`tvloader`).

**Comment by swinslow** [comment]
Hi @abhishekspeer, I am having some trouble pushing commits to amend the PR. It is failing because Travis is failing to install libraptor, which is required for goraptor to work.

Could you please push another commit onto your branch that makes the following change?

In .travis.yml, please add the following after line 4:
```
addons:
  apt:
    packages:
      - libraptor2-dev
```

And then push that commit to your branch, which I hope will update this PR and re-run the tests successfully  :)

**Comment by abhishekspeer** [comment]
@swinslow that was exactly where I was stuck! Thanks a lot for helping me with this one. :)
I've made the changes and all the checks have passed now.

**Comment by swinslow** [comment]
Great! I will go ahead and merge this into the rdfreader branch. Thanks @abhishekspeer!

**Pull request merged**
