### PR TITLE
Included Unit Test for chain.go

### PR DESCRIPTION
**Pull request by neilnaveen**
- Included unit tests for `convert/chain.go`

Signed-off-by: Neil Naveen <42328488+neilnaveen@users.noreply.github.com>

### CODE REVIEW

**Comment by kzantow** [comment]
Hi @neilnaveen and thanks for the contribution. I'm curious what is this supposed to be testing, though? There are already [a number of tests for the go-struct-converter library](https://github.com/anchore/go-struct-converter/blob/main/chain_test.go), which this is somewhat duplicating.

**Comment by neilnaveen** [comment]
> Hi @neilnaveen and thanks for the contribution. I'm curious what is this supposed to be testing, though? There are already [a number of tests for the go-struct-converter library](https://github.com/anchore/go-struct-converter/blob/main/chain_test.go), which this is somewhat duplicating.

I wasn't aware of this, my intention was to add coverage to to chain.go.

By including these test, I do not think it would be detrimental. Thoughts?

Thanks

**Comment by kzantow** [comment]
I'm _definitely_ not against adding more tests! I think what might be better here is to update the [spdx_document_conversion_test.go](https://github.com/spdx/tools-golang/blob/main/convert/spdx_document_conversion_test.go#L2117) to use `convert.Document`, as this is already a much more thorough test. What do you think?

**Comment by neilnaveen** [comment]
> I'm _definitely_ not against adding more tests! I think what might be better here is to update the [spdx_document_conversion_test.go](https://github.com/spdx/tools-golang/blob/main/convert/spdx_document_conversion_test.go#L2117) to use `convert.Document`, as this is already a much more thorough test. What do you think?

Thanks, but I feel that adding more to this large test file would make hard to contribute(especially for new contributors) to as well as maintain on a later date. Thoughts?

**Comment by kzantow** [comment]
@neilnaveen it wouldn't be adding anything more, just [changing the call on the line I referenced](https://github.com/spdx/tools-golang/blob/main/convert/spdx_document_conversion_test.go#L2117) from:
```go
err := converter.Convert(test.source, outInstance)
```
to
```go
err := Document(test.source, outInstance)
```

**Comment by kzantow** [comment]
@neilnaveen I've implemented the suggestion in this PR: https://github.com/spdx/tools-golang/pull/184 -- it exercises the whole conversion chain now on complete SPDX documents (it should have done this before). It is distinctly possible at some point in the future that the `common.Document` interface might become something other than just `interface{}`, which all the SPDX Document objects implement. This would force the only objects passed into `convert.Document` to be actual SPDX documents rather than arbitrary types this test has. Do you see a need for something more than what's provided in #184?

**Comment by neilnaveen** [comment]
> @neilnaveen I've implemented the suggestion in this PR: #184 -- it exercises the whole conversion chain now on complete SPDX documents (it should have done this before). It is distinctly possible at some point in the future that the `common.Document` interface might become something other than just `interface{}`, which all the SPDX Document objects implement. This would force the only objects passed into `convert.Document` to be actual SPDX documents rather than arbitrary types this test has. Do you see a need for something more than what's provided in #184?

No, though I would have appreciated being able to fix this issue, since I am a new contributor to this project.

**Comment by lumjjb** [comment]
hi @neilnaveen appreciate the gesture, we very much want to encourage external contributions. I'd suggest:

- If @kzantow is amicable, to add a co-authored with you
- We have some additional issues that are existing, which we would recommend tackling, if you spot an issue that you think needs to be worked on, we encourage to open an issue first before submitting a PR, since there may be additional context around it or other work that others can help chime in on. This prevents situations where your effort wouldn't get wasted (e.g. planning to deprecate/refactor a certain function, etc.). 

A few issues that come to mind that may be good first issues to tackle are:
- https://github.com/spdx/tools-golang/issues/182
- https://github.com/spdx/tools-golang/issues/177

**Comment by kzantow** [comment]
@neilnaveen I'm happy to close PR #184 if you'd like to update this one 👍

**Comment by neilnaveen** [comment]
> @neilnaveen I'm happy to close PR #184 if you'd like to update this one 👍

I do not want you to close the PR, I will work on the other issues.

**Comment by neilnaveen** [comment]
> hi @neilnaveen appreciate the gesture, we very much want to encourage external contributions. I'd suggest:
> 
> * If @kzantow is amicable, to add a co-authored with you
> * We have some additional issues that are existing, which we would recommend tackling, if you spot an issue that you think needs to be worked on, we encourage to open an issue first before submitting a PR, since there may be additional context around it or other work that others can help chime in on. This prevents situations where your effort wouldn't get wasted (e.g. planning to deprecate/refactor a certain function, etc.).
> 
> A few issues that come to mind that may be good first issues to tackle are:
> 
> * [tagvalue parser incorrectly complains about DocumentComment #182](https://github.com/spdx/tools-golang/issues/182)
> * [jsonloader: panic error when parsing creation info #177](https://github.com/spdx/tools-golang/issues/177)

@lumjjb Thank you, I will work on the issues stated. I do not need to be a co-author.

**Comment by lumjjb** [comment]
Resolved by #184

**Pull request closed without merging**
