### PR TITLE
Support more checksum algorithms

### LINKED ISSUE #96: [tvloader] got unknown checksum type SHA512
Unable to parse the following SPDX file with `tvloader` package:

```
...
SPDXID: SPDXRef-File-34182904f819889b086a855ee5878f2a2e0b9037
FileChecksum: SHA1: 335029255dbadc3dfeb15c8e432078b1535b90de
FileChecksum: SHA256: 0852707ebbd7e78d71c1eea3fb7ac0348aa22124a8975f787c07217058e0fe20
FileChecksum: SHA512: 2bca030aeb4aff21505267c02230bbc91bea728070fe6b46089eb7c168deeb6e0d40195a307d8e39073f322cba7abaf81a1b92011ca249eba2b8d92aedc10e38
...
```

Got the following error:
```log
WARN[0000] got unknown checksum type SHA512
```

### PR DESCRIPTION
**Pull request by ianling**
Depends on and contains commits from #134, #135, #137, and #138 

Allows all the known checksum algorithms in the enum to be considered valid.

Fixes #96

### CODE REVIEW

**Comment by jdolitsky** [comment]
Hi, any update on this PR? Just ran into #96 converting a tv doc to JSON:
```
got unknown checksum type SHA512 
```

**Comment by jdolitsky** [comment]
Can confirm this PR fixes the error related to SHA512

**Comment by ianling** [comment]
@jdolitsky there are a couple more PRs in the pipeline ahead of this one, but we'll get to it! Sorry for the delay.

**Comment by jdolitsky** [comment]
appreciate the update @ianling !

**Comment by lumjjb** [comment]
Hi @ianling just checking in back on this!

**Pull request closed without merging**
