### PR TITLE
Create Go Module

### PR DESCRIPTION
**Pull request by RishabhBhatnagar**
- Unpack directory v0 to move all the content to the root directory.
 - ./v0/* converted to ./*
 - all the test cases were fixed to remove one directory less indexing for test files
 - add go.mod
 - go version 1.13 is used to have a relatively stable versioning system

### CODE REVIEW

**Comment by rtgdk** [comment]
@RishabhBhatnagar Good work. Can you post a successful test run screenshot? Also, it would be great if you could do the same with `rdfreader` branch (maybe in a new PR). Also, it would be great if you can show how would the module be imported in some other project or you can just build a test project and import tools-golang as a module and try out its different function.

**Comment by RishabhBhatnagar** [comment]
[gist::demo.go](https://gist.github.com/RishabhBhatnagar/cfa6f2df661e37e4a1f306e900e8dd88) is the way the module can be used. This gist demonstrates only two packages namely `builder` and `idsearcher`. The remaining packages can be used in a similar manner.


Some common questions regarding this update:
1. **How to get a specific version of the module?**
`go get github.com/spdx/tools-golang@version_tag`
For example: `go get github.com/spdx/tools-golang@v0.0.0`

02. **Getting the latest version of the module**
    `go get -u ./...` This command upgrades all the dependencies.

3. **Semantic Versioning:**
   - For the current version(v0), version name is not required in the import statement as demonstrated in the gist.
   -  Starting from v2, It is necessary to add the version number in the import package.
        For example `import "github.com/spdx/tools-golang/v2/builder"`
   - Different aliases can be used to import the same package from different versions.
        For example: 
        <pre>import (
            v0Builder "github.com/spdx/tools-golang/builder"
            v2Builder "github.com/spdx/tools-golang/v2/builder"
        )</pre>
4. Once the PR is merged with the master Branch, One can install the spdx module using
    `go get "github.com/spdx/tools-golang"`


### Terminal Output showing Successful run of all the tests in the module:
image

**Comment by rtgdk** [comment]
@RishabhBhatnagar  Great work! Can you do the same with `rdfreader` branch? Also, how do we manage the version tag `@version_tag` ? Is there a file where we can update the version tag or do we use the github releases?

**Comment by RishabhBhatnagar** [comment]
I'm extremely sorry for the late reply.
As far as I've read about [versioning modules in golang](https://github.com/golang/go/wiki/Modules), they use git-releases for managing versions.

**Comment by swinslow** [comment]
Hi @RishabhBhatnagar, thanks very much for the hard work in pulling all this together. I apologize that I haven't had time yet to review it closely. I will try to do so in the next few days and if all looks good then I'll merge the PR, otherwise I'll circle back with feedback. Really appreciate you helping to move this forward!

**Comment by RishabhBhatnagar** [comment]
> Hi @RishabhBhatnagar, thanks very much for the hard work in pulling all this together. I apologize that I haven't had time yet to review it closely. I will try to do so in the next few days and if all looks good then I'll merge the PR, otherwise I'll circle back with feedback. Really appreciate you helping to move this forward!

Kindly confirm the merging status and let me know if any improvements are needed.

**Comment by swinslow** [comment]
Hi @RishabhBhatnagar, this was a very good PR. I've reviewed and I don't see any changes needed before merging, so I will merge it now. Thanks for taking the time to move this forward, and well done!

**Pull request merged**
